### ISSUE TITLE
Change a follower site to the new leader site

### ISSUE THREAD

**Issue by ciobancai** [avinetworks/devops#240]
Hi,

It is possible to be provided an example of changing a follower site to become the leader site, I tried to use the below gslb task and it doesn't work. The only option / doc found it is https://avinetworks.com/docs/20.1/how-to-select-a-leader-site-manually/

We are using avi 20.1.6 with ansible 2.8
For the moment we have the old avi that is configured to be gslb site leader and the new avi as gslb site follower and we want to switch by making the avi as leader and old avi to be follower. We tried the below task but is not doing anything and we do not received any error.

```
    - name: Switch gslb site leaeder
      avi_gslb:
        controller: "new controler ip"
        username: "{{ avi_username }}"
        password: "{{ avi_password }}"
        api_version: "20.1.6"
        avi_api_update_method: patch
        avi_api_patch_op: replace
        state: present
        name: "AVI-gslb-{{ availability_zone }}"
        leader_cluster_uuid: "{{ cls_rtn_obj_new.obj.uuid }}"
        sites:
          - name: "{{ dc }}-gslb-{{ availability_zone }}-site_new"
            username: "{{ avi_username }}"
            password: "{{ avi_password }}"
            ip_addresses:
              - type: "V4"
                addr: "10.231.1.91"
              - type: "V4"
                addr: "10.231.2.170"
              - type: "V4"
                addr: "10.231.0.48"
            dns_vses:
              - dns_vs_uuid: "{{ vs_rtn_obj_new.obj.results.0.uuid }}"
            enabled: True
            member_type: "GSLB_ACTIVE_MEMBER"
            port: 443
            cluster_uuid: "{{ cls_rtn_obj_new.obj.uuid }}"
          - name: "{{ dc }}-gslb-{{ availability_zone }}-site_old"
            username: "{{ avi_username }}"
            password: "{{ avi_password }}"
            ip_addresses:
              - type: "V4"
                addr: "10.231.0.230"
              - type: "V4"
                addr: "10.231.2.135"
              - type: "V4"
                addr: "10.231.1.121"
            dns_vses:
              - dns_vs_uuid: "{{ vs_rtn_obj_old.obj.results.0.uuid }}"
            enabled: True
            member_type: "GSLB_ACTIVE_MEMBER"
            port: 443
            cluster_uuid: "{{ cls_rtn_obj_old.obj.uuid }}"
```

Please let us know if you need more details

Thank you,
Vlad
